sonar.projectKey=ffreis-rust-onnx-model-serving
sonar.organization=felipefuhr


# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=ffreis-rust-onnx-model
# sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=./app
sonar.rust.lcov.reportPaths=coverage/lcov.info

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8