name: DevOps / Release Please

on:
  push:
    branches: [main]
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release-please:
    permissions:
      contents: write
      pull-requests: write
      issues: write
    uses: ffreis-org/ffreis-workflows-general/.github/workflows/general-release-please.yml@287f836a726a35af37bd24561fc687f66eaeb92f # v1.7.0
    with:
      config-file: .release-please-config.json
      manifest-file: .release-please-manifest.json
      target-branch: main
    secrets:
      RELEASE_PLEASE_TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN }}
