name: Code Quality (SonarCloud)

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "**/*.rs"
      - "Cargo.toml"
      - "Cargo.lock"
      - "sonar-project.properties"
      - ".github/workflows/**"
  push:
    branches: [main]
    paths:
      - "**/*.rs"
      - "Cargo.toml"
      - "Cargo.lock"
      - "sonar-project.properties"
      - ".github/workflows/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  sonar:
    if: ${{ !github.event.pull_request.draft && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false) }}
    permissions:
      contents: read
    uses: FelipeFuhr/ffreis-workflows-rust/.github/workflows/rust-sonar.yml@98d5d139853a40c6ae4175ead25a5b09e4130104 # main
    with:
      working-directory: .
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
